spring:
 application:
  name: gab

 datasource:
  url: ${DB_URL}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: org.postgresql.Driver

 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKey12345678901234567890}
    expiration: ${JWT_EXPIRATION:86400000}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  success-url: ${STRIPE_FRONTEND_SUCCESS}
  cancel-url: ${STRIPE_FRONTEND_CANCEL}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
