const books = [
  {
    title: '1984',
    author: 'George Orwell',
    price: 38000,
    genre: 'Ficción',
    rating: 4.8,
    description: 'Una novela distópica sobre vigilancia y control estatal.',
    image: 'https://m.media-amazon.com/images/I/41yetK0QkzL.jpg',
  },
  {
    title: 'Matar a un ruiseñor',
    author: 'Harper Lee',
    price: 47000,
    genre: 'Drama',
    rating: 4.7,
    description: 'Un clásico que aborda el racismo y la justicia en EE.UU.',
    image: 'https://m.media-amazon.com/images/I/81Od4SzxboL.AC_UF1000,1000_QL80.jpg',
  },
  {
    title: 'Orgullo y prejuicio',
    author: 'Jane Austen',
    price: 32000,
    genre: 'Romance',
    rating: 4.6,
    description: 'Una historia de amor y malentendidos en la Inglaterra del siglo XIX.',
    image: 'https://m.media-amazon.com/images/I/51zr1Pa8-EL.AC_UF894,1000_QL80.jpg',
  },
  {
    title: 'El Gran Gatsby',
    author: 'F. Scott Fitzgerald',
    price: 41000,
    genre: 'Ficción',
    rating: 4.5,
    description: 'Una crítica a la sociedad americana durante los años 20.',
    image: 'https://m.media-amazon.com/images/I/51wV79SpJyL.jpg',
  },
  {
    title: 'Harry Potter y la piedra filosofal',
    author: 'J.K. Rowling',
    price: 78000,
    genre: 'Fantasía',
    rating: 4.9,
    description: 'La primera entrega de la saga del joven mago Harry Potter.',
    image: 'https://m.media-amazon.com/images/I/81YOuOGFCJL.AC_UF1000,1000_QL80.jpg',
  },
  {
    title: 'Mujercitas',
    author: 'Louisa May Alcott',
    price: 39000,
    genre: 'Drama',
    rating: 4.6,
    description: 'Las hermanas March enfrentan la vida, el amor y los retos de crecer.',
    image: 'https://m.media-amazon.com/images/I/51i1PRyP3mL.jpg',
  },
  {
    title: 'El alquimista',
    author: 'Paulo Coelho',
    price: 42000,
    genre: 'Aventura',
    rating: 4.3,
    description: 'Un joven pastor en busca de su leyenda personal.',
    image: 'https://m.media-amazon.com/images/I/51Z0nLAfLmL.jpg',
  },
  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    price: 58000,
    genre: 'Realismo Mágico',
    rating: 4.9,
    description: 'La historia épica de la familia Buendía en Macondo.',
    image: 'https://m.media-amazon.com/images/I/91o4ztdO6yL.AC_UF1000,1000_QL80.jpg',
  },
];

export default books;
